source 'https://rubygems.org'
ruby '2.1.0'

gem 'sinatra', require: 'sinatra/base'
gem 'rack-standards'
gem 'unicorn'
gem 'i18n'
gem 'activesupport'
gem 'rake'
gem 'builder'
gem 'json', '~> 1.7.7'
gem 'dotenv'
gem 'selenium-webdriver'
gem 'linkedin2'
gem 'redis'
